### ISSUE TITLE
Error when executed script for switching protractor to cypress

### ISSUE THREAD

**Issue by vrknetha** [skylock/cypress-angular-coverage-example#11]
```
ng g @briebug/cypress-schematic:cypress true
```
When i tried to run the above script i got the below error
```
An unhandled exception occurred: Schematic "cypress" not found in collection "@briebug/cypress-schematic".
See "C:\****\Local\Temp\ng-8DnsCc\angular-errors.log" for further details.
```

**Comment by bindea-mihai** [comment]
Had the same issue too, apparently the right command is 
`ng add @briebug/cypress-schematic`

Found this while checking their repository https://github.com/briebug/cypress-schematic

**Comment by skylock** [comment]
Thank you ! Update README.
