### ISSUE TITLE
window._coverage_ variable not generated.

### ISSUE THREAD

**Issue by DimitriCourtoisAcelys** [skylock/cypress-angular-coverage-example#3]
Hi, thanks for you're example, it's really helpfull.
But if i clone your repo and then lauch cypress (and the app) i do not see the varaible _coverage_ inside the window object...

I would like to have this variable because it's necessary for one of my CI which contains Cypress tests (indeed Cypres test are not stored inside the app but inside an other repo and call throught a CI).

**Comment by D0rmouse** [comment]
Probably you need to 

```
module.exports = (on, config) => {
  require('@cypress/code-coverage/task')(on, config)
  // IMPORTANT to return the config object
  // with the any changed environment variables
  return config
}
```
But I can't recommend the using istanbul-instrumenter-loader, because it uses a really old instanbul-lib-instrument.
