### ISSUE TITLE
Where does each piece go?

### ISSUE THREAD

**Issue by alastair-todd** [skylock/cypress-angular-coverage-example#4]
I have a project where our e2e folder containing cypress and test code is independent of the main angular app (it has its own package.json effectively).

So I am not sure which bit goes where from the instructions.

I can see the instrumentation stuff will need to live on the angular side, then it goes a bit blurry.

Could someone point me in the right direction please?

**Comment by swathishetty** [comment]
@alastair-todd where you able to generate coverage for your project ? I am also facing the same issue. I have a different folder structure and cypress tests are present in a separate independent repository. @skylock Any help would be appreciated. Thank you

**Comment by alastair-todd** [comment]
@swathishetty yes I did - as long as the project is being `ng served` using the example here it is fine. you do most of the setting up on your e2e project

I've also updated the loader to the one used by the angular team as it seems to offer better support for source maps - in fact i've now managed to include an angular library in my coverage (with a hack on istanbul-lib-report which Im currently working on)

These are the dependencies:

web app
```
coverage-istanbul-loader // update this in the webpack.config file which needs to be in the web app
ngx-build-plus
```

e2e
```
@cypress/code-coverage
@istanbuljs/nyc-config-typescript
istanbul-lib-coverage
nyc
```

add the nyc config to the e2e package.json

```
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true
  },

```
