### ISSUE TITLE
How to instrument an angular library?

### ISSUE THREAD

**Issue by alastair-todd** [skylock/cypress-angular-coverage-example#5]
How do I go about including coverage for a whole workspace - that's 2 projects: 1 library and 1 web app?

**Comment by maddy619** [comment]
I also have a similar(ish) question, my app component is just a shell, I have generated the angular components as packages and deployed in dist, then I fetch it from dist into shell app component, cypress covers the app component not the components I have imported, need to cover those too..! Any help..!

**Comment by skylock** [comment]
This is out of this demo repo scope.
