### ISSUE TITLE
Fix documentation with new registration api for task.

### ISSUE THREAD

**Issue by franckstifler** [skylock/cypress-angular-coverage-example#7]
Replace the `  on('task', require('@cypress/code-coverage/task'))` with the new api `  require('@cypress/code-coverage/task')(on, config);
  return config` else, the task will not be registered.

**Comment by abhidp** [comment]
> Replace the ` on('task', require('@cypress/code-coverage/task'))` with the new api ` require('@cypress/code-coverage/task')(on, config); return config` else, the task will not be registered.

Created a PR for this : https://github.com/skylock/cypress-angular-coverage-example/pull/10

**Comment by skylock** [comment]
> > Replace the ` on('task', require('@cypress/code-coverage/task'))` with the new api ` require('@cypress/code-coverage/task')(on, config); return config` else, the task will not be registered.
> 
> Created a PR for this : #10

Thank you for your contribution !
