### ISSUE TITLE
how to instrument the angular code and run cypress test when application and cypress test are in different repositories

### ISSUE THREAD

**Issue by swathishetty** [skylock/cypress-angular-coverage-example#8]
I have a different folder structure and cypress tests are present in a separate independent repository. @skylock Any help would be appreciated. Thank you

**Comment by skylock** [comment]
You basically want to :
1. instrument the app code
2. Run the app with the instrumented code
3. Check you have ___coverage__  object available
4. Add code coverage plugin to cypress
5. Run cypress tests and collect code coverage
6. Map the collected coverage results to your app source files, if not done automatically

For examples, please see : [ https://docs.cypress.io/guides/tooling/code-coverage.html#Introduction ](Cypress Code Coverage)
