### ISSUE TITLE
Using this example, what is instrumenting html files?

### ISSUE THREAD

**Issue by jameseg** [skylock/cypress-angular-coverage-example#9]
I've followed this example and my report is showing html files alongside the .ts files.

![image](https://user-images.githubusercontent.com/38703245/81332555-43b71e80-9071-11ea-9385-1981697a9475.png)

I've confirmed with the istanbuljs/nyc folks and they said none of the istanbuljs tools directly support generating coverage for scripts inside the HTML files and that something else must be instrumenting the HTML files.

Any idea what that could be or how I can exclude them?

**Comment by skylock** [comment]
To exclude files from the report it is an nyc setting. In your package.json file under nyc settings add a exclude array with the files you want to be excluded.

e.g.

  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "exclude": [
      "src/main.ts"
    ]
  }
